name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          profile: minimal
          toolchain: nightly-2022-04-01

      - uses: Swatinem/rust-cache@v1

      - run: ./scripts/tests.sh
